[project]
name = "h2ctypes"
version = "0.1.0"
description = "convert c++ header files to python ctypes"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "typer"
]

[project.scripts]
h2ctypes_dump = "h2ctypes.dump:app"
